### ISSUE TITLE
Make I/O graph open as part of a specific context only

### ISSUE THREAD

**Issue by un1versal** [kvirc/KVIrc#1968]
The I/O graph only works if you only connect to one network and open the IO graph, soon as there are various connected networks it doesnt know what to do and does nothing instead.

**Comment by IceN9ne** [comment]
There was a bug where connections using SSL weren't tracked in the I/O graph.  This was fixed in 86ac8eb.

I'm assuming that your issue was due to some of your networks being SSL and some being non-SSL.  If you could retest that and confirm the issue you're seeing for this ticket is resolved, please let us know.

**Comment by un1versal** [comment]
all only ssl, one uses znc but still ssl, yes I still see this issue after https://github.com/kvirc/KVIrc/commit/86ac8eb36bbf1933ab3a5125076a36eb19a55116
