### ISSUE TITLE
Notifier Background Color Issue

### ISSUE THREAD

**Issue by erictinney** [kvirc/KVIrc#2294]
### Expected behavior
Expected notifier to use background colors as set in Settings > Theme Preferences > Notifier

### Actual behavior
When notifier appears, the background color set in preferences is ignored and text appears on a white background, regardless of settings in theme preferences. Screenshot at http://erictinney.com/kvirc-screenshot.png 

[//]:# (Besides the text description, include any screenshots that help us visualize the issue you're facing
http://erictinney.com/kvirc-screenshot.png
![kvirc-screenshot](https://user-images.githubusercontent.com/22227627/29953706-f25bc5d2-8e97-11e7-93c0-8c3420841119.png)

### Steps to reproduce the issue
1. Set notifier background color in Settings > Configure Theme > Notifier
2. Apply changes then click OK
3. When the notifier appears in response to a message, the background color is not the same as it is set in settings.

### System information
[//]:# (Type ```/about.kvirc``` or click "Help → About KVIrc" and copy & paste the details from the "Executable Information" tab below between ``` marks)  
[//]:# (Also Enter any OS information the "Executable Information" tab doesn't contain, e.g. KDE, Gentoo, Linux Mint, etc.)

```
KVIrc 4.9.2 'Aria'

Runtime Info:
System name: Linux 4.4.0-93-generic
System version: #116-Ubuntu SMP Fri Aug 11 21:17:51 UTC 2017
Architecture: x86_64
Qt version: 5.5.1
Qt theme: fusion

Build Info:
Build date: 2017-08-31 14:15:39 UTC
Sources date: 20160102
Revision number: git-7181-g692d10d9d
System name: Linux-4.4.0-92-generic
CPU name: x86_64
Build command: /usr/bin/cmake
Build flags: 
   MANDIR=share/man
   CMAKE_INSTALL_PREFIX=/usr
   LIB_SUFFIX=/x86_64-linux-gnu
   Threads=POSIX
Compiler name: /usr/bin/x86_64-linux-gnu-g++
Compiler flags: -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 
Qt version: 5.5.1
Features: IRC, Debug, IPv6, Crypt, SSL, IfAddr, IPC, Transparency, Phonon, Webkit, DCCVoice, Perl, Python, Enchant, Qt5, KVS

Ubuntu 16.04 LTS
```
[//]:# (If you experienced crashes or segfaults please also include a stacktrace below, For how-to read: https://github.com/kvirc/KVIrc/wiki/Grabbing-a-useful-backtrace.)

**Comment by erictinney** [comment]
![kvirc-screenshot](https://user-images.githubusercontent.com/22227627/29953631-7b04f616-8e97-11e7-954f-7cad8e7337c2.png)

**Comment by IceN9ne** [comment]
This was broken when style.css was fixed.  When a stylesheet is loaded, it affects things that use the QPalette.

Renaming the style.css file so that it isn't loaded fixes the issue.

**Comment by erictinney** [comment]
Opening a terminal window and renaming /usr/share/kvirc/4.9/config/style.css worked:

> **sudo mv /usr/share/kvirc/4.9/config/style.css /usr/share/kvirc/4.9/config/_style.css**

Thank you, IceN9ne, for this fix.

**Comment by miseryburiedalive** [comment]
Not fixed for:
Runtime Info:
System name: Linux 4.12.12-gentoo
System version: #1 SMP Mon Oct 9 11:27:46 +07 2017
Architecture: x86_64
Qt version: 5.7.1
Qt theme: fusion

Build Info:
Build date: 2017-12-06 09:30:19 UTC
Sources date: 20160102
Revision number: 150eeeab99ce7f340bf17e337b7ef1357ba375ad
System name: Linux-4.12.12-gentoo
CPU name: x86_64
Build command: /usr/bin/cmake
Build flags: 
   MANDIR=share/man
   CMAKE_INSTALL_PREFIX=/usr
   VERBOSE
   LIB_SUFFIX=64
   Threads=POSIX
Compiler name: /usr/bin/x86_64-pc-linux-gnu-g++
Compiler flags: -O2 -march=native -pipe -fno-strict-aliasing
Qt version: 5.7.1
Features: IRC, IPv6, Crypt, SSL, IfAddr, IPC, Transparency, Phonon, DCCVoice, Perl, Python, Enchant, Qt5, KVS

**Comment by wodim** [comment]
As I said to you, this bug is open, because we are aware it is not fixed yet.
