### ISSUE TITLE
user lists width changed after restart

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#823]
**Reported by nucleo on 23 Jun 2010 18:55:16 UTC**
Width of user lists on some of autojoin channels changed after restart in http://labs.pragmaware.net/misc/kvirc-4.0.0.tar.bz2 (r4489)

Need to resize them after every restart.

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/823

**Comment by DarthGandalf** [comment]
**Comment by HelLViS69 on 27 Jun 2010 15:35:41**
confirmed on r4533

**Comment by DarthGandalf** [comment]
**Modified by pragmaware on 27 Jun 2010 16:07:24**
Resolution: none → invalid
Status: new → closed

**Comment by DarthGandalf** [comment]
**Modified by pragmaware on 27 Jun 2010 16:07:38**
Resolution: invalid → none
Status: closed → reopened

**Comment by DarthGandalf** [comment]
**Modified by pragmaware on 27 Jun 2010 16:08:05**
Resolution: none → invalid
Status: reopened → closed

**Comment by DarthGandalf** [comment]
**Comment by pragmaware on 27 Jun 2010 16:19:37**
Jeez.. :D

---

Resolution: invalid → none
Status: closed → reopened

**Comment by DarthGandalf** [comment]
**Comment by ctrlaltca on 27 Jun 2010 20:05:02**
removed 2 old hacks in r4537, it should work better now

---

Resolution: none → fixed
Status: reopened → closed

**Comment by DarthGandalf** [comment]
**Comment by anonymous on 28 Jun 2010 13:21:37**
Bug not fixed in r4541.

Also width of channel modes not saved after restart:

http://img571.imageshack.us/img571/6915/userlist.png

---

Resolution: fixed → none
Status: closed → reopened

**Comment by DarthGandalf** [comment]
**Modified by nucleo on 28 Jun 2010 13:32:11**

**Comment by DarthGandalf** [comment]
**Comment by nucleo on 28 Jun 2010 15:10:37**
I removed #kde from autojoin list but the same on other affected channels. When I joined to #kde there was narrow userlist, I changed list size and leaved channel. When I joined again list size was saved. And when I added it to autojoin list size was saved too.

**Comment by DarthGandalf** [comment]
**Comment by Cronus on 04 Jul 2010 07:56:12**
This is very annoying and im on windows... :\

**Comment by DarthGandalf** [comment]
**Comment by gizmokid2005 on 05 Jul 2010 18:54:06**
I just figured I'd add to this, this is an issue for me on both windows and OSX, but I've also noticed that the chanmode textbox does the same thing (in this screenie, the chanmode box was just as wide as the userlist was): http://gizmokid2005.com/images/kvirc_chanmode_width.png

**Comment by DarthGandalf** [comment]
**Comment by Cronus on 05 Jul 2010 21:00:19**
Yes the chanmode textbox was all the way to the left completely hiding the channel topic

**Comment by DarthGandalf** [comment]
**Comment by ctrlaltca on 20 Jul 2010 09:05:08**
hopefully fixed in r4681. Some explanation regarding the problem: <br/>
Open kvirc, go into SDI mode (maximize the mdi window), then connect to a network and join a test channel: this channel will open and gets maximized, too.<br/>
Now, double click the channel in the window list, so that it will gets minimized. Qt4 will nicely draw a shaded (i.e. collapsed on the titlebar) window in the bottom left corner of the mdi area.<br/>
To do this, qt4 will change the geometry of the window to a very small size (like 196x28 in my tests). When you restore that minimized window, qt4 somehow restores the previous (correct) geometry of the window, too.<br/>
Unfortunately this seems not to always work, so you may end up with a windows that's no more minimized but has that ridiculous small size (rounded up to its minimumSize()). You don't notice this because the windows get restored as maximized, but its geometry is screwed.<br/>
Then you close kvirc, and reopen it, connect and rejoin the channel.. at the moment of recreating that infamous window, kvirc will try to restore that small geometry and place all the widgets inside it. Since there's not enough room for everything, every widget gets resized to its minimumSize(). Then the window gets maximized and shown, but the widgets inside it are screwed.<br/>
Workaround adopted: use a plain show() instead that the more correct showNormal() when de-minimizing mdi windows; show() seems not to enforce any (good or bad) window geometry.
Sorry for the wall of text :)

---

Resolution: none → fixed
Status: reopened → closed

**Comment by DarthGandalf** [comment]
**Comment by nucleo on 20 Jul 2010 10:14:26**
Not fixed yet. Userlist size saved if I close it at least once before exit from kvirc.  This issue  related only to channels that was opened at first in old snapshots before 4.0.0 release.

**Comment by un1versal** [comment]
duplicate of https://github.com/kvirc/KVIrc/issues/900
