### ISSUE TITLE
Icons do not render in popup menu items or echos

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#949]
**Reported by OmegaPhil on 06 Sep 2010 15:49:10 UTC**
According to the documentation, you can render an icon in a popup item by passing a signed integer 'icon identifier' after the text to display.

The following example code creates an appropriate popup menu and sets it as the first item in the menubar:

```
defpopup ("ciao") {
    item("Test",$icon("accept")) echo "Clicked!"
}

setmenu "ciao", ciao
```

When viewed in the Popup Editor (http://a.imageshack.us/img828/2990/kvircbugkvirc411equilib.png), the 'Test' item is rendered with a tick icon, however when you browse to the popup in KVIrc's GUI, the icon is not rendered (http://a.imageshack.us/img412/2990/kvircbugkvirc411equilib.png). This has been tested on mIRC v1.4.1 and YellowIRC v1.0.0 themes (the mIRC theme is the one I use).

Incase imageshack fails, screenshots are also attached.

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/949

**Comment by DarthGandalf** [comment]
**Comment by anonymous on 06 Sep 2010 16:07:05**
Icons do not appear in echos either, e.g. this should include an icon but doesn't:

```
/echo -i=$msgtype("parsererror") this has the colors of the parser error messages
```

**Comment by DarthGandalf** [comment]
**Modified by OmegaPhil on 06 Sep 2010 16:07:36**
Summary: Icons do not render in popup menu items → Icons do not render in popup menu items or echos

**Comment by DarthGandalf** [comment]
**Modified by ctrlaltca on 18 Sep 2010 17:00:39**
Version: none → 4.1 Equilibrium

**Comment by DarthGandalf** [comment]
**Comment by ctrlaltca on 31 Oct 2010 17:59:03**
While nobody else has been able to reproduce this behaviour, it could has been solved avoiding the use of gtkstyle. Please test a version >= r5123

---

Resolution: none → need feedback
Status: new → closed

**Comment by DarthGandalf** [comment]
**Modified by Omega on 06 Nov 2010 17:52:43**

**Comment by DarthGandalf** [comment]
**Comment by Omega on 06 Nov 2010 17:59:25**
I am now using r5125 - I can confirm this is still a problem.

---

Resolution: need feedback → none
Status: closed → reopened

**Comment by DarthGandalf** [comment]
**Comment by ctrlaltca on 13 Mar 2011 19:23:37**
Again, can you test a revision >= 5578 ? something related has been fixed

**Comment by DarthGandalf** [comment]
**Comment by Omega on 13 Mar 2011 19:54:33**
I can confirm with both the popup and echo examples that icons still do not appear (r5581 tested).

**Comment by DarthGandalf** [comment]
**Comment by Omega on 21 Mar 2011 19:30:55**
Even though Im still on r5581, the icons now almost completely work! All popup icons appear to work (associated with the main menu, channel menu, etc), however the previous echo example:

```
/echo -i=$msgtype("parsererror") this has the colors of the parser error messages
```

continues not to work.

**Comment by un1versal** [comment]
This may be fixed now in master.

**Comment by un1versal** [comment]
This is fixed in 4.3.2 current master has no such issue on Windows or Linux. Closing as fixed.
